root: true
plugins:
  - jest
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
env:
  browser: false
  commonjs: false
  es2022: true
  jest/globals: false
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
overrides: []
parserOptions:
  project: "tsconfig.json"
ignorePatterns:
  - "build/**/*"
  - "register-swc.js"
  - "migrate.js"
rules:
  curly: "error"
