plugins:
  - jest
  - "@typescript-eslint"
env:
  browser: false
  commonjs: false
  es2021: true
  jest/globals: false
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ["build/**/*"]
rules:
  curly: "error"
